//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int id { get; set; }
        public int id_TypePartner { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string email { get; set; }
        public string NumberPartner { get; set; }
        public string Adress { get; set; }
        public Nullable<long> INN { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual TypePartner TypePartner { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
