//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.RequestItems = new HashSet<RequestItems>();
        }
    
        public int id { get; set; }
        public int id_TypeProduct { get; set; }
        public string Name { get; set; }
        public long Articyl { get; set; }
        public decimal MinSumPartner { get; set; }
    
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual ICollection<RequestItems> RequestItems { get; set; }
    }
}
