//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.RequestItems = new HashSet<RequestItems>();
        }
    
        public int id { get; set; }
        public int id_Partner { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual ICollection<RequestItems> RequestItems { get; set; }
    }
}
